export const extensionIconPath: { [key: string]: string } = {
  html: '../../icons/html',
  css: '../../icons/css',
  js: '../../icons/javascript',
  ts: '../../icons/typescript',
  tsx: '../../icons/react_ts',
  jsx: '../../icons/react',
  json: '../../icons/json',
  png: '../../icons/image',
  jpg: '../../icons/image',
  jpeg: '../../icons/jpeg',
  gif: '../../icons/gif',
  svg: '../../icons/svg',
  pdf: '../../icons/pdf',
  txt: '../../icons/document',
  zip: '../../icons/zip',
  rar: '../../icons/rar',
  doc: '../../icons/doc',
  docx: '../../icons/docx',
  md: '../../icons/readme',
  less: '../../icons/less',
  scss: '../../icons/sass',
  config: '../../icons/settings',
  license: '../../icons/certificate',
  ico: '../../icons/favicon',
  // Compound extensions
  'package-lock.json': '../../icons/json',
  'tsconfig.json': '../../icons/tsconfig',
  'vite.config.ts': '../../icons/vite',
  'package.json': '../../icons/json',
  gitignore: '../../icons/git',
  dockerfile: '../../icons/docker',
  dockerignore: '../../icons/docker',
  env: '../../icons/tune',
  '.env.example': '../../icons/tune',

  // Folder icons
  folder: '../../icons/folder',
  node_modules: '../../icons/folder-node',
  public: '../../icons/folder-public',
  src: '../../icons/folder-src',
  git: '../../icons/folder-git', // لمجلد .git
  tests: '../../icons/folder-test',
  assets: '../../icons/folder-resource',
  components: '../../icons/folder-components',
  styles: '../../icons/folder-css',
  pages: '../../icons/folder-views',
  ui: '../../icons/folder-ui',
  layouts: '../../icons/folder-layouts',
  utils: '../../icons/folder-utils',
  hooks: '../../icons/folder-hooks',
  contexts: '../../icons/folder-contexts',
  services: '../../icons/folder-services',
  constants: '../../icons/folder-constants',
  reducers: '../../icons/folder-reducers',
  actions: '../../icons/folder-actions',
  middlewares: '../../icons/folder-middlewares',
  stores: '../../icons/folder-stores',
  routes: '../../icons/folder-routes',
  helpers: '../../icons/folder-helpers',
  locales: '../../icons/folder-locales',
  locales_en: '../../icons/folder-locales',
  locales_ar: '../../icons/folder-locales',
  locales_fr: '../../icons/folder-locales',
  locales_es: '../../icons/folder-locales',
  locales_de: '../../icons/folder-locales',
  locales_it: '../../icons/folder-locales',
  locales_pt: '../../icons/folder-locales',
  locales_ru: '../../icons/folder-locales',
  locales_zh: '../../icons/folder-locales',
  locales_ja: '../../icons/folder-locales',
  locales_ko: '../../icons/folder-locales',
  locales_tr: '../../icons/folder-locales',
  locales_pl: '../../icons/folder-locales',
  locales_nl: '../../icons/folder-locales',
  locales_sv: '../../icons/folder-locales',
  locales_no: '../../icons/folder-locales',
  locales_da: '../../icons/folder-locales',
  locales_fi: '../../icons/folder-locales',
  locales_cs: '../../icons/folder-locales',
  locales_hu: '../../icons/folder-locales',

  locales_ro: '../../icons/folder-locales',
  locales_sk: '../../icons/folder-locales',
  locales_bg: '../../icons/folder-locales',
  locales_hr: '../../icons/folder-locales',

  locales_sl: '../../icons/folder-locales',
  locales_lt: '../../icons/folder-locales',
  locales_lv: '../../icons/folder-locales',
  locales_et: '../../icons/folder-locales',
};

export const appIconsPath: { [key: string]: string } = {
  close: '../../vsc-icons/dark/close.svg',
  chevronDown: '../../vsc-icons/dark/chevron-down.svg',
  chevronRight: '../../vsc-icons/dark/chevron-right.svg',
  vscode: '../../icons/vscode.svg',
  ellipsis: '../../vsc-icons/dark/ellipsis.svg',
};
